export const libraryFilterMessages: Record<string, Record<string, string>> = {
"Favourite": {ar:"المفضلة",bg:"Любими","zh-Hans":"收藏","zh-Hant":"收藏",cs:"Oblíbené",da:"Favorit",nl:"Favoriet",fi:"Suosikki",fr:"Favori",de:"Favorit",el:"Αγαπημένο",hu:"Kedvenc",id:"Favorit",it:"Preferito",ja:"お気に入り",ko:"즐겨찾기",no:"Favoritt",pl:"Ulubione",pt:"Favorito","pt-BR":"Favorito",ro:"Favorit",ru:"Избранное",es:"Favorito",sv:"Favorit",th:"รายการโปรด",tr:"Favori",uk:"Улюблене",vi:"Yêu thích"},
"Played": {ar:"تم لعبها",bg:"Играно","zh-Hans":"已玩","zh-Hant":"已玩",cs:"Hráno",da:"Spillet",nl:"Gespeeld",fi:"Pelattu",fr:"Joué",de:"Gespielt",el:"Παίχτηκε",hu:"Játszott",id:"Dimainkan",it:"Giocato",ja:"プレイ済み",ko:"플레이함",no:"Spilt",pl:"Grano",pt:"Jogado","pt-BR":"Jogado",ro:"Jucat",ru:"Играли",es:"Jugado",sv:"Spelat",th:"เล่นแล้ว",tr:"Oynandı",uk:"Зіграно",vi:"Đã chơi"},
"Never": {ar:"أبدًا",bg:"Никога","zh-Hans":"从未","zh-Hant":"從未",cs:"Nikdy",da:"Aldrig",nl:"Nooit",fi:"Ei koskaan",fr:"Jamais",de:"Nie",el:"Ποτέ",hu:"Soha",id:"Tidak pernah",it:"Mai",ja:"未プレイ",ko:"한 번도 안 함",no:"Aldri",pl:"Nigdy",pt:"Nunca","pt-BR":"Nunca",ro:"Niciodată",ru:"Никогда",es:"Nunca",sv:"Aldrig",th:"ไม่เคย",tr:"Asla",uk:"Ніколи",vi:"Chưa bao giờ"},
"Already": {ar:"بالفعل",bg:"Вече","zh-Hans":"已经","zh-Hant":"已經",cs:"Již",da:"Allerede",nl:"Al",fi:"Jo",fr:"Déjà",de:"Bereits",el:"Ήδη",hu:"Már",id:"Sudah",it:"Già",ja:"すでに",ko:"이미",no:"Allerede",pl:"Już",pt:"Já","pt-BR":"Já",ro:"Deja",ru:"Уже",es:"Ya",sv:"Redan",th:"แล้ว",tr:"Zaten",uk:"Вже",vi:"Đã"},
"Any": {ar:"أي",bg:"Всеки","zh-Hans":"任意","zh-Hant":"任意",cs:"Libovolný",da:"Enhver",nl:"Elke",fi:"Mikä tahansa",fr:"N’importe lequel",de:"Beliebig",el:"Οποιοδήποτε",hu:"Bármelyik",id:"Apa saja",it:"Qualsiasi",ja:"すべて",ko:"모두",no:"Hvilken som helst",pl:"Dowolne",pt:"Qualquer","pt-BR":"Qualquer",ro:"Oricare",ru:"Любой",es:"Cualquiera",sv:"Valfri",th:"ใดก็ได้",tr:"Herhangi",uk:"Будь-який",vi:"Bất kỳ"},
"Library filters": {ar:"عوامل تصفية المكتبة",bg:"Филтри на библиотеката","zh-Hans":"游戏库筛选器","zh-Hant":"遊戲庫篩選器",cs:"Filtry knihovny",da:"Biblioteksfiltre",nl:"Bibliotheekfilters",fi:"Kirjaston suodattimet",fr:"Filtres de la bibliothèque",de:"Bibliotheksfilter",el:"Φίλτρα βιβλιοθήκης",hu:"Könyvtárszűrők",id:"Filter pustaka",it:"Filtri della libreria",ja:"ライブラリフィルター",ko:"라이브러리 필터",no:"Bibliotekfiltre",pl:"Filtry biblioteki",pt:"Filtros da biblioteca","pt-BR":"Filtros da biblioteca",ro:"Filtrele bibliotecii",ru:"Фильтры библиотеки",es:"Filtros de biblioteca",sv:"Biblioteksfilter",th:"ตัวกรองคลังเกม",tr:"Kitaplık filtreleri",uk:"Фільтри бібліотеки",vi:"Bộ lọc thư viện"},
"Smart filters": {ar:"عوامل التصفية الذكية",bg:"Интелигентни филтри","zh-Hans":"智能筛选器","zh-Hant":"智慧篩選器",cs:"Chytré filtry",da:"Smarte filtre",nl:"Slimme filters",fi:"Älykkäät suodattimet",fr:"Filtres intelligents",de:"Intelligente Filter",el:"Έξυπνα φίλτρα",hu:"Intelligens szűrők",id:"Filter pintar",it:"Filtri intelligenti",ja:"スマートフィルター",ko:"스마트 필터",no:"Smarte filtre",pl:"Inteligentne filtry",pt:"Filtros inteligentes","pt-BR":"Filtros inteligentes",ro:"Filtre inteligente",ru:"Умные фильтры",es:"Filtros inteligentes",sv:"Smarta filter",th:"ตัวกรองอัจฉริยะ",tr:"Akıllı filtreler",uk:"Розумні фільтри",vi:"Bộ lọc thông minh"},
"Saved filters": {ar:"عوامل التصفية المحفوظة",bg:"Запазени филтри","zh-Hans":"已保存的筛选器","zh-Hant":"已儲存的篩選器",cs:"Uložené filtry",da:"Gemte filtre",nl:"Opgeslagen filters",fi:"Tallennetut suodattimet",fr:"Filtres enregistrés",de:"Gespeicherte Filter",el:"Αποθηκευμένα φίλτρα",hu:"Mentett szűrők",id:"Filter tersimpan",it:"Filtri salvati",ja:"保存済みフィルター",ko:"저장된 필터",no:"Lagrede filtre",pl:"Zapisane filtry",pt:"Filtros guardados","pt-BR":"Filtros salvos",ro:"Filtre salvate",ru:"Сохранённые фильтры",es:"Filtros guardados",sv:"Sparade filter",th:"ตัวกรองที่บันทึกไว้",tr:"Kaydedilen filtreler",uk:"Збережені фільтри",vi:"Bộ lọc đã lưu"},
"Sources and collections": {ar:"المصادر والمجموعات",bg:"Източници и колекции","zh-Hans":"来源和收藏集","zh-Hant":"來源與收藏集",cs:"Zdroje a kolekce",da:"Kilder og samlinger",nl:"Bronnen en collecties",fi:"Lähteet ja kokoelmat",fr:"Sources et collections",de:"Quellen und Sammlungen",el:"Πηγές και συλλογές",hu:"Források és gyűjtemények",id:"Sumber dan koleksi",it:"Fonti e collezioni",ja:"ソースとコレクション",ko:"소스 및 컬렉션",no:"Kilder og samlinger",pl:"Źródła i kolekcje",pt:"Fontes e coleções","pt-BR":"Fontes e coleções",ro:"Surse și colecții",ru:"Источники и коллекции",es:"Fuentes y colecciones",sv:"Källor och samlingar",th:"แหล่งที่มาและคอลเลกชัน",tr:"Kaynaklar ve koleksiyonlar",uk:"Джерела й колекції",vi:"Nguồn và bộ sưu tập"},
"Note (optional)": {ar:"ملاحظة (اختياري)",bg:"Бележка (по избор)","zh-Hans":"备注（可选）","zh-Hant":"備註（選填）",cs:"Poznámka (volitelné)",da:"Note (valgfri)",nl:"Notitie (optioneel)",fi:"Muistiinpano (valinnainen)",fr:"Note (facultatif)",de:"Notiz (optional)",el:"Σημείωση (προαιρετικό)",hu:"Megjegyzés (nem kötelező)",id:"Catatan (opsional)",it:"Nota (facoltativa)",ja:"メモ（任意）",ko:"메모(선택 사항)",no:"Notat (valgfritt)",pl:"Notatka (opcjonalnie)",pt:"Nota (opcional)","pt-BR":"Nota (opcional)",ro:"Notă (opțional)",ru:"Заметка (необязательно)",es:"Nota (opcional)",sv:"Anteckning (valfritt)",th:"บันทึก (ไม่บังคับ)",tr:"Not (isteğe bağlı)",uk:"Примітка (необов’язково)",vi:"Ghi chú (không bắt buộc)"},
"Note": {ar:"ملاحظة",bg:"Бележка","zh-Hans":"备注","zh-Hant":"備註",cs:"Poznámka",da:"Note",nl:"Notitie",fi:"Muistiinpano",fr:"Note",de:"Notiz",el:"Σημείωση",hu:"Megjegyzés",id:"Catatan",it:"Nota",ja:"メモ",ko:"메모",no:"Notat",pl:"Notatka",pt:"Nota","pt-BR":"Nota",ro:"Notă",ru:"Заметка",es:"Nota",sv:"Anteckning",th:"บันทึก",tr:"Not",uk:"Примітка",vi:"Ghi chú"},
"Added": {ar:"تمت الإضافة",bg:"Добавено","zh-Hans":"已添加","zh-Hant":"已新增",cs:"Přidáno",da:"Tilføjet",nl:"Toegevoegd",fi:"Lisätty",fr:"Ajouté",de:"Hinzugefügt",el:"Προστέθηκε",hu:"Hozzáadva",id:"Ditambahkan",it:"Aggiunto",ja:"追加済み",ko:"추가됨",no:"Lagt til",pl:"Dodano",pt:"Adicionado","pt-BR":"Adicionado",ro:"Adăugat",ru:"Добавлено",es:"Añadido",sv:"Tillagd",th:"เพิ่มแล้ว",tr:"Eklendi",uk:"Додано",vi:"Đã thêm"},
"Reset to automatic": {ar:"إعادة إلى التلقائي",bg:"Връщане към автоматично","zh-Hans":"重置为自动","zh-Hant":"重設為自動",cs:"Obnovit automatické",da:"Nulstil til automatisk",nl:"Terugzetten op automatisch",fi:"Palauta automaattiseksi",fr:"Rétablir l’automatique",de:"Auf automatisch zurücksetzen",el:"Επαναφορά σε αυτόματο",hu:"Visszaállítás automatikusra",id:"Atur ulang ke otomatis",it:"Ripristina automatico",ja:"自動に戻す",ko:"자동으로 재설정",no:"Tilbakestill til automatisk",pl:"Przywróć automatyczne",pt:"Repor automático","pt-BR":"Redefinir para automático",ro:"Resetează la automat",ru:"Сбросить на автоматический режим",es:"Restablecer automático",sv:"Återställ till automatiskt",th:"รีเซ็ตเป็นอัตโนมัติ",tr:"Otomatiğe sıfırla",uk:"Скинути до автоматичного",vi:"Đặt lại tự động"},
"Edited by you.": {ar:"تم التعديل بواسطتك.",bg:"Редактирано от вас.","zh-Hans":"由你编辑。","zh-Hant":"由你編輯。",cs:"Upraveno vámi.",da:"Redigeret af dig.",nl:"Door jou bewerkt.",fi:"Sinun muokkaamasi.",fr:"Modifié par vous.",de:"Von dir bearbeitet.",el:"Επεξεργάστηκε από εσάς.",hu:"Általad szerkesztve.",id:"Diedit oleh Anda.",it:"Modificato da te.",ja:"あなたが編集しました。",ko:"직접 수정했습니다.",no:"Redigert av deg.",pl:"Edytowane przez Ciebie.",pt:"Editado por ti.","pt-BR":"Editado por você.",ro:"Editat de tine.",ru:"Отредактировано вами.",es:"Editado por ti.",sv:"Redigerad av dig.",th:"แก้ไขโดยคุณ",tr:"Sizin tarafınızdan düzenlendi.",uk:"Відредаговано вами.",vi:"Bạn đã chỉnh sửa."}
};