export const setupMessages: Record<string, Record<string, string>> = {
  "Your games, your way.": { ar: "ألعابك، بطريقتك.", bg: "Твоите игри, по твоя начин.", "zh-Hans": "你的游戏，由你做主。", "zh-Hant": "你的遊戲，由你作主。", cs: "Tvé hry, tvůj způsob.", da: "Dine spil, på din måde.", nl: "Jouw games, jouw manier.", fi: "Sinun pelisi, omalla tavallasi.", fr: "Vos jeux, à votre façon.", de: "Deine Spiele, dein Stil.", el: "Τα παιχνίδια σου, όπως τα θέλεις.", hu: "A játékaid, a te módodon.", id: "Game-mu, caramu.", it: "I tuoi giochi, a modo tuo.", ja: "あなたのゲームを、あなたらしく。", ko: "나만의 방식으로 즐기는 게임.", no: "Dine spill, på din måte.", pl: "Twoje gry, na Twoich zasadach.", pt: "Os teus jogos, à tua maneira.", "pt-BR": "Seus jogos, do seu jeito.", ro: "Jocurile tale, în felul tău.", ru: "Твои игры — по твоим правилам.", es: "Tus juegos, a tu manera.", sv: "Dina spel, på ditt sätt.", th: "เกมของคุณ ในแบบของคุณ", tr: "Oyunların, senin tarzın.", uk: "Твої ігри — за твоїми правилами.", vi: "Trò chơi của bạn, theo cách của bạn." },
  "Choose your language.": { ar: "اختر لغتك.", bg: "Изберете език.", "zh-Hans": "选择你的语言。", "zh-Hant": "選擇你的語言。", cs: "Vyberte jazyk.", da: "Vælg dit sprog.", nl: "Kies je taal.", fi: "Valitse kieli.", fr: "Choisissez votre langue.", de: "Wähle deine Sprache.", el: "Επιλέξτε τη γλώσσα σας.", hu: "Válaszd ki a nyelvet.", id: "Pilih bahasa Anda.", it: "Scegli la lingua.", ja: "言語を選択してください。", ko: "언어를 선택하세요.", no: "Velg språk.", pl: "Wybierz język.", pt: "Escolhe o teu idioma.", "pt-BR": "Escolha seu idioma.", ro: "Alege limba.", ru: "Выберите язык.", es: "Elige tu idioma.", sv: "Välj språk.", th: "เลือกภาษาของคุณ", tr: "Dilini seç.", uk: "Виберіть мову.", vi: "Chọn ngôn ngữ." },
  "Choose your theme.": { ar: "اختر السمة.", bg: "Изберете тема.", "zh-Hans": "选择主题。", "zh-Hant": "選擇主題。", cs: "Vyberte motiv.", da: "Vælg dit tema.", nl: "Kies je thema.", fi: "Valitse teema.", fr: "Choisissez votre thème.", de: "Wähle dein Design.", el: "Επιλέξτε θέμα.", hu: "Válassz témát.", id: "Pilih tema.", it: "Scegli il tema.", ja: "テーマを選択してください。", ko: "테마를 선택하세요.", no: "Velg tema.", pl: "Wybierz motyw.", pt: "Escolhe o teu tema.", "pt-BR": "Escolha seu tema.", ro: "Alege tema.", ru: "Выберите тему.", es: "Elige tu tema.", sv: "Välj tema.", th: "เลือกธีม", tr: "Temanı seç.", uk: "Виберіть тему.", vi: "Chọn giao diện." },
  "Make Mochi comfortable.": { ar: "اجعل Mochi مريحًا لك.", bg: "Настройте Mochi за вашия комфорт.", "zh-Hans": "让 Mochi 更适合你。", "zh-Hant": "讓 Mochi 更適合你。", cs: "Přizpůsobte si Mochi.", da: "Gør Mochi behagelig at bruge.", nl: "Maak Mochi comfortabel.", fi: "Tee Mochista mukava käyttää.", fr: "Personnalisez votre confort dans Mochi.", de: "Passe Mochi an deine Bedürfnisse an.", el: "Κάντε το Mochi πιο άνετο για εσάς.", hu: "Tedd kényelmessé a Mochit.", id: "Buat Mochi nyaman digunakan.", it: "Rendi Mochi più confortevole.", ja: "Mochi を使いやすく設定しましょう。", ko: "Mochi를 편안하게 사용하도록 설정하세요.", no: "Gjør Mochi behagelig å bruke.", pl: "Dostosuj Mochi do swoich potrzeb.", pt: "Torna o Mochi mais confortável.", "pt-BR": "Deixe o Mochi mais confortável.", ro: "Personalizează confortul în Mochi.", ru: "Настройте Mochi под себя.", es: "Adapta Mochi a tus preferencias.", sv: "Gör Mochi bekvämt att använda.", th: "ปรับ Mochi ให้ใช้งานสบายขึ้น", tr: "Mochi'yi kendin için rahat hale getir.", uk: "Налаштуйте Mochi для зручного користування.", vi: "Tùy chỉnh Mochi để sử dụng thoải mái." },
  "Find your games.": { ar: "اعثر على ألعابك.", bg: "Намерете игрите си.", "zh-Hans": "查找你的游戏。", "zh-Hant": "尋找你的遊戲。", cs: "Najděte své hry.", da: "Find dine spil.", nl: "Vind je games.", fi: "Etsi pelisi.", fr: "Trouvez vos jeux.", de: "Finde deine Spiele.", el: "Βρείτε τα παιχνίδια σας.", hu: "Keresd meg a játékaidat.", id: "Temukan game Anda.", it: "Trova i tuoi giochi.", ja: "ゲームを見つけましょう。", ko: "게임을 찾아보세요.", no: "Finn spillene dine.", pl: "Znajdź swoje gry.", pt: "Encontra os teus jogos.", "pt-BR": "Encontre seus jogos.", ro: "Găsește-ți jocurile.", ru: "Найдите свои игры.", es: "Encuentra tus juegos.", sv: "Hitta dina spel.", th: "ค้นหาเกมของคุณ", tr: "Oyunlarını bul.", uk: "Знайдіть свої ігри.", vi: "Tìm trò chơi của bạn." },

  "Connected": { ar: "متصل", bg: "Свързано", "zh-Hans": "已连接", "zh-Hant": "已連線", cs: "Připojeno", da: "Forbundet", nl: "Verbonden", fi: "Yhdistetty", fr: "Connecté", de: "Verbunden", el: "Συνδεδεμένο", hu: "Csatlakoztatva", id: "Terhubung", it: "Connesso", ja: "接続済み", ko: "연결됨", no: "Tilkoblet", pl: "Połączono", pt: "Ligado", "pt-BR": "Conectado", ro: "Conectat", ru: "Подключено", es: "Conectado", sv: "Ansluten", th: "เชื่อมต่อแล้ว", tr: "Bağlandı", uk: "Підключено", vi: "Đã kết nối" }
,

  "Main navigation": { ar: "التنقل الرئيسي", bg: "Основна навигация", "zh-Hans": "主导航", "zh-Hant": "主導覽", cs: "Hlavní navigace", da: "Hovednavigation", nl: "Hoofdnavigatie", fi: "Päänavigointi", fr: "Navigation principale", de: "Hauptnavigation", el: "Κύρια πλοήγηση", hu: "Fő navigáció", id: "Navigasi utama", it: "Navigazione principale", ja: "メインナビゲーション", ko: "기본 탐색", no: "Hovednavigasjon", pl: "Nawigacja główna", pt: "Navegação principal", "pt-BR": "Navegação principal", ro: "Navigare principală", ru: "Основная навигация", es: "Navegación principal", sv: "Huvudnavigering", th: "การนำทางหลัก", tr: "Ana gezinme", uk: "Основна навігація", vi: "Điều hướng chính" },
  "Cloud library": { ar: "مكتبة السحابة", bg: "Облачна библиотека", "zh-Hans": "云端游戏库", "zh-Hant": "雲端遊戲庫", cs: "Cloudová knihovna", da: "Skybibliotek", nl: "Cloudbibliotheek", fi: "Pilvikirjasto", fr: "Bibliothèque cloud", de: "Cloud-Bibliothek", el: "Βιβλιοθήκη cloud", hu: "Felhőkönyvtár", id: "Pustaka cloud", it: "Libreria cloud", ja: "クラウドライブラリ", ko: "클라우드 라이브러리", no: "Skybibliotek", pl: "Biblioteka w chmurze", pt: "Biblioteca na nuvem", "pt-BR": "Biblioteca na nuvem", ro: "Bibliotecă în cloud", ru: "Облачная библиотека", es: "Biblioteca en la nube", sv: "Molnbibliotek", th: "คลังเกมบนคลาวด์", tr: "Bulut kitaplığı", uk: "Хмарна бібліотека", vi: "Thư viện đám mây" },
  "Game services": { ar: "خدمات الألعاب", bg: "Игрови услуги", "zh-Hans": "游戏服务", "zh-Hant": "遊戲服務", cs: "Herní služby", da: "Spiltjenester", nl: "Gameservices", fi: "Pelipalvelut", fr: "Services de jeu", de: "Spieledienste", el: "Υπηρεσίες παιχνιδιών", hu: "Játékszolgáltatások", id: "Layanan game", it: "Servizi di gioco", ja: "ゲームサービス", ko: "게임 서비스", no: "Spilltjenester", pl: "Usługi gier", pt: "Serviços de jogos", "pt-BR": "Serviços de jogos", ro: "Servicii pentru jocuri", ru: "Игровые сервисы", es: "Servicios de juegos", sv: "Speltjänster", th: "บริการเกม", tr: "Oyun hizmetleri", uk: "Ігрові служби", vi: "Dịch vụ trò chơi" },
  "Search languages…": { ar: "ابحث عن اللغات…", bg: "Търсене на езици…", "zh-Hans": "搜索语言…", "zh-Hant": "搜尋語言…", cs: "Hledat jazyky…", da: "Søg efter sprog…", nl: "Talen zoeken…", fi: "Hae kieliä…", fr: "Rechercher des langues…", de: "Sprachen suchen…", el: "Αναζήτηση γλωσσών…", hu: "Nyelvek keresése…", id: "Cari bahasa…", it: "Cerca lingue…", ja: "言語を検索…", ko: "언어 검색…", no: "Søk etter språk…", pl: "Szukaj języków…", pt: "Pesquisar idiomas…", "pt-BR": "Pesquisar idiomas…", ro: "Caută limbi…", ru: "Поиск языков…", es: "Buscar idiomas…", sv: "Sök språk…", th: "ค้นหาภาษา…", tr: "Dil ara…", uk: "Пошук мов…", vi: "Tìm ngôn ngữ…" },
  "Light": { ar: "فاتح", bg: "Светла", "zh-Hans": "浅色", "zh-Hant": "淺色", cs: "Světlý", da: "Lys", nl: "Licht", fi: "Vaalea", fr: "Clair", de: "Hell", el: "Ανοιχτό", hu: "Világos", id: "Terang", it: "Chiaro", ja: "ライト", ko: "라이트", no: "Lys", pl: "Jasny", pt: "Claro", "pt-BR": "Claro", ro: "Luminos", ru: "Светлая", es: "Claro", sv: "Ljust", th: "สว่าง", tr: "Açık", uk: "Світла", vi: "Sáng" },
  "Dark": { ar: "داكن", bg: "Тъмна", "zh-Hans": "深色", "zh-Hant": "深色", cs: "Tmavý", da: "Mørk", nl: "Donker", fi: "Tumma", fr: "Sombre", de: "Dunkel", el: "Σκούρο", hu: "Sötét", id: "Gelap", it: "Scuro", ja: "ダーク", ko: "다크", no: "Mørk", pl: "Ciemny", pt: "Escuro", "pt-BR": "Escuro", ro: "Întunecat", ru: "Тёмная", es: "Oscuro", sv: "Mörkt", th: "มืด", tr: "Koyu", uk: "Темна", vi: "Tối" }

};
