export const settingsTitleExtraMessages: Record<string, Record<string, string>> = {
  "Security": { ar: "الأمان", bg: "Сигурност", "zh-Hans": "安全", "zh-Hant": "安全性", cs: "Zabezpečení", da: "Sikkerhed", nl: "Beveiliging", fi: "Tietoturva", fr: "Sécurité", de: "Sicherheit", el: "Ασφάλεια", hu: "Biztonság", id: "Keamanan", it: "Sicurezza", ja: "セキュリティ", ko: "보안", no: "Sikkerhet", pl: "Bezpieczeństwo", pt: "Segurança", "pt-BR": "Segurança", ro: "Securitate", ru: "Безопасность", es: "Seguridad", sv: "Säkerhet", th: "ความปลอดภัย", tr: "Güvenlik", uk: "Безпека", vi: "Bảo mật" },
  "Achievements": { ar: "الإنجازات", bg: "Постижения", "zh-Hans": "成就", "zh-Hant": "成就", cs: "Úspěchy", da: "Præstationer", nl: "Prestaties", fi: "Saavutukset", fr: "Succès", de: "Erfolge", el: "Επιτεύγματα", hu: "Eredmények", id: "Pencapaian", it: "Obiettivi", ja: "実績", ko: "업적", no: "Prestasjoner", pl: "Osiągnięcia", pt: "Conquistas", "pt-BR": "Conquistas", ro: "Realizări", ru: "Достижения", es: "Logros", sv: "Prestationer", th: "ความสำเร็จ", tr: "Başarımlar", uk: "Досягнення", vi: "Thành tựu" },
  "Updates": { ar: "التحديثات", bg: "Актуализации", "zh-Hans": "更新", "zh-Hant": "更新", cs: "Aktualizace", da: "Opdateringer", nl: "Updates", fi: "Päivitykset", fr: "Mises à jour", de: "Updates", el: "Ενημερώσεις", hu: "Frissítések", id: "Pembaruan", it: "Aggiornamenti", ja: "更新", ko: "업데이트", no: "Oppdateringer", pl: "Aktualizacje", pt: "Atualizações", "pt-BR": "Atualizações", ro: "Actualizări", ru: "Обновления", es: "Actualizaciones", sv: "Uppdateringar", th: "อัปเดต", tr: "Güncellemeler", uk: "Оновлення", vi: "Cập nhật" },
  "Experimental": { ar: "تجريبي", bg: "Експериментално", "zh-Hans": "实验功能", "zh-Hant": "實驗功能", cs: "Experimentální", da: "Eksperimentelt", nl: "Experimenteel", fi: "Kokeelliset", fr: "Expérimental", de: "Experimentell", el: "Πειραματικά", hu: "Kísérleti", id: "Eksperimental", it: "Sperimentale", ja: "実験的機能", ko: "실험적 기능", no: "Eksperimentelt", pl: "Eksperymentalne", pt: "Experimental", "pt-BR": "Experimental", ro: "Experimental", ru: "Экспериментальное", es: "Experimental", sv: "Experimentellt", th: "ทดลอง", tr: "Deneysel", uk: "Експериментальне", vi: "Thử nghiệm" },
  "Sound": { ar: "الصوت", bg: "Звук", "zh-Hans": "声音", "zh-Hant": "音效", cs: "Zvuk", da: "Lyd", nl: "Geluid", fi: "Ääni", fr: "Son", de: "Sound", el: "Ήχος", hu: "Hang", id: "Suara", it: "Audio", ja: "サウンド", ko: "사운드", no: "Lyd", pl: "Dźwięk", pt: "Som", "pt-BR": "Som", ro: "Sunet", ru: "Звук", es: "Sonido", sv: "Ljud", th: "เสียง", tr: "Ses", uk: "Звук", vi: "Âm thanh" },
  "Storage": { ar: "التخزين", bg: "Съхранение", "zh-Hans": "存储", "zh-Hant": "儲存空間", cs: "Úložiště", da: "Lagerplads", nl: "Opslag", fi: "Tallennustila", fr: "Stockage", de: "Speicher", el: "Αποθήκευση", hu: "Tárhely", id: "Penyimpanan", it: "Archiviazione", ja: "ストレージ", ko: "저장 공간", no: "Lagring", pl: "Pamięć", pt: "Armazenamento", "pt-BR": "Armazenamento", ro: "Stocare", ru: "Хранилище", es: "Almacenamiento", sv: "Lagring", th: "พื้นที่จัดเก็บ", tr: "Depolama", uk: "Сховище", vi: "Lưu trữ" },
  "Plugins": { ar: "الإضافات", bg: "Приставки", "zh-Hans": "插件", "zh-Hant": "外掛程式", cs: "Doplňky", da: "Plugins", nl: "Plug-ins", fi: "Lisäosat", fr: "Extensions", de: "Plugins", el: "Πρόσθετα", hu: "Bővítmények", id: "Plugin", it: "Plugin", ja: "プラグイン", ko: "플러그인", no: "Programtillegg", pl: "Wtyczki", pt: "Plugins", "pt-BR": "Plugins", ro: "Pluginuri", ru: "Плагины", es: "Complementos", sv: "Tillägg", th: "ปลั๊กอิน", tr: "Eklentiler", uk: "Плагіни", vi: "Plugin" },
  "Controller": { ar: "وحدة التحكم", bg: "Контролер", "zh-Hans": "控制器", "zh-Hant": "控制器", cs: "Ovladač", da: "Controller", nl: "Controller", fi: "Ohjain", fr: "Manette", de: "Controller", el: "Χειριστήριο", hu: "Kontroller", id: "Kontroler", it: "Controller", ja: "コントローラー", ko: "컨트롤러", no: "Kontroller", pl: "Kontroler", pt: "Comando", "pt-BR": "Controle", ro: "Controler", ru: "Контроллер", es: "Mando", sv: "Handkontroll", th: "คอนโทรลเลอร์", tr: "Kontrolcü", uk: "Контролер", vi: "Bộ điều khiển" }
};
