export const accessibilityExtraMessages: Record<string, Record<string, string>> = {
  "On": { ar: "تشغيل", bg: "Включено", "zh-Hans": "开", "zh-Hant": "開啟", cs: "Zapnuto", da: "Til", nl: "Aan", fi: "Päällä", fr: "Activé", de: "Ein", el: "Ενεργό", hu: "Be", id: "Aktif", it: "Attivo", ja: "オン", ko: "켜짐", no: "På", pl: "Wł.", pt: "Ligado", "pt-BR": "Ativado", ro: "Pornit", ru: "Вкл.", es: "Activado", sv: "På", th: "เปิด", tr: "Açık", uk: "Увімк.", vi: "Bật" },
  "Off": { ar: "إيقاف", bg: "Изключено", "zh-Hans": "关", "zh-Hant": "關閉", cs: "Vypnuto", da: "Fra", nl: "Uit", fi: "Pois", fr: "Désactivé", de: "Aus", el: "Ανενεργό", hu: "Ki", id: "Nonaktif", it: "Disattivo", ja: "オフ", ko: "꺼짐", no: "Av", pl: "Wył.", pt: "Desligado", "pt-BR": "Desativado", ro: "Oprit", ru: "Выкл.", es: "Desactivado", sv: "Av", th: "ปิด", tr: "Kapalı", uk: "Вимк.", vi: "Tắt" },
  "Normal": { ar: "عادي", bg: "Нормално", "zh-Hans": "标准", "zh-Hant": "標準", cs: "Normální", da: "Normal", nl: "Normaal", fi: "Normaali", fr: "Normal", de: "Normal", el: "Κανονικό", hu: "Normál", id: "Normal", it: "Normale", ja: "標準", ko: "보통", no: "Normal", pl: "Normalny", pt: "Normal", "pt-BR": "Normal", ro: "Normal", ru: "Обычный", es: "Normal", sv: "Normal", th: "ปกติ", tr: "Normal", uk: "Звичайний", vi: "Bình thường" },
  "Thick": { ar: "سميك", bg: "Дебел", "zh-Hans": "粗", "zh-Hant": "粗", cs: "Silný", da: "Tykkere", nl: "Dik", fi: "Paksu", fr: "Épais", de: "Dick", el: "Παχύ", hu: "Vastag", id: "Tebal", it: "Spesso", ja: "太い", ko: "두껍게", no: "Tykk", pl: "Gruby", pt: "Espesso", "pt-BR": "Espesso", ro: "Gros", ru: "Толстый", es: "Grueso", sv: "Tjock", th: "หนา", tr: "Kalın", uk: "Товстий", vi: "Dày" },
  "Extra thick": { ar: "سميك جدًا", bg: "Много дебел", "zh-Hans": "特粗", "zh-Hant": "特粗", cs: "Velmi silný", da: "Ekstra tyk", nl: "Extra dik", fi: "Erittäin paksu", fr: "Très épais", de: "Extra dick", el: "Πολύ παχύ", hu: "Extra vastag", id: "Sangat tebal", it: "Molto spesso", ja: "極太", ko: "매우 두껍게", no: "Ekstra tykk", pl: "Bardzo gruby", pt: "Muito espesso", "pt-BR": "Extra espesso", ro: "Foarte gros", ru: "Очень толстый", es: "Muy grueso", sv: "Extra tjock", th: "หนามาก", tr: "Çok kalın", uk: "Дуже товстий", vi: "Rất dày" },
  "Deuteranopia": { ar: "عمى الأخضر", bg: "Дейтеранопия", "zh-Hans": "绿色盲", "zh-Hant": "綠色盲", cs: "Deuteranopie", da: "Deuteranopi", nl: "Deuteranopie", fi: "Deuteranopia", fr: "Deutéranopie", de: "Deuteranopie", el: "Δευτερανωπία", hu: "Deuteranópia", id: "Deuteranopia", it: "Deuteranopia", ja: "第二色覚異常", ko: "녹색맹", no: "Deuteranopi", pl: "Deuteranopia", pt: "Deuteranopia", "pt-BR": "Deuteranopia", ro: "Deuteranopie", ru: "Дейтеранопия", es: "Deuteranopía", sv: "Deuteranopi", th: "ตาบอดสีเขียว", tr: "Döteranopi", uk: "Дейтеранопія", vi: "Mù màu xanh lục" },
  "Protanopia": { ar: "عمى الأحمر", bg: "Протанопия", "zh-Hans": "红色盲", "zh-Hant": "紅色盲", cs: "Protanopie", da: "Protanopi", nl: "Protanopie", fi: "Protanopia", fr: "Protanopie", de: "Protanopie", el: "Πρωτανωπία", hu: "Protanópia", id: "Protanopia", it: "Protanopia", ja: "第一色覚異常", ko: "적색맹", no: "Protanopi", pl: "Protanopia", pt: "Protanopia", "pt-BR": "Protanopia", ro: "Protanopie", ru: "Протанопия", es: "Protanopía", sv: "Protanopi", th: "ตาบอดสีแดง", tr: "Protanopi", uk: "Протанопія", vi: "Mù màu đỏ" },
  "Tritanopia": { ar: "عمى الأزرق", bg: "Тританопия", "zh-Hans": "蓝黄色盲", "zh-Hant": "藍黃色盲", cs: "Tritanopie", da: "Tritanopi", nl: "Tritanopie", fi: "Tritanopia", fr: "Tritanopie", de: "Tritanopie", el: "Τριτανωπία", hu: "Tritanópia", id: "Tritanopia", it: "Tritanopia", ja: "第三色覚異常", ko: "청황색맹", no: "Tritanopi", pl: "Tritanopia", pt: "Tritanopia", "pt-BR": "Tritanopia", ro: "Tritanopie", ru: "Тританопия", es: "Tritanopía", sv: "Tritanopi", th: "ตาบอดสีน้ำเงิน", tr: "Tritanopi", uk: "Тританопія", vi: "Mù màu xanh lam" },
  "Atkinson Hyperlegible, easier to tell letters apart.": { ar: "خط Atkinson Hyperlegible، يسهل تمييز الحروف.", bg: "Шрифтът Atkinson Hyperlegible улеснява различаването на буквите.", "zh-Hans": "Atkinson Hyperlegible 字体更容易区分字母。", "zh-Hant": "Atkinson Hyperlegible 字型讓字母更容易區分。", cs: "Písmo Atkinson Hyperlegible usnadňuje rozlišování písmen.", da: "Atkinson Hyperlegible gør det lettere at skelne bogstaver fra hinanden.", nl: "Atkinson Hyperlegible maakt letters makkelijker van elkaar te onderscheiden.", fi: "Atkinson Hyperlegible helpottaa kirjainten erottamista toisistaan.", fr: "La police Atkinson Hyperlegible permet de mieux distinguer les lettres.", de: "Atkinson Hyperlegible erleichtert die Unterscheidung von Buchstaben.", el: "Η γραμματοσειρά Atkinson Hyperlegible διευκολύνει τη διάκριση των γραμμάτων.", hu: "Az Atkinson Hyperlegible betűtípussal könnyebb megkülönböztetni a betűket.", id: "Atkinson Hyperlegible memudahkan membedakan huruf.", it: "Atkinson Hyperlegible aiuta a distinguere meglio le lettere.", ja: "Atkinson Hyperlegible は文字を見分けやすいフォントです。", ko: "Atkinson Hyperlegible은 글자를 더 쉽게 구분할 수 있는 글꼴입니다.", no: "Atkinson Hyperlegible gjør det enklere å skille bokstaver fra hverandre.", pl: "Atkinson Hyperlegible ułatwia odróżnianie liter.", pt: "Atkinson Hyperlegible facilita a distinção entre letras.", "pt-BR": "Atkinson Hyperlegible facilita a distinção entre letras.", ro: "Atkinson Hyperlegible face literele mai ușor de diferențiat.", ru: "Atkinson Hyperlegible облегчает различение букв.", es: "Atkinson Hyperlegible facilita distinguir las letras.", sv: "Atkinson Hyperlegible gör det lättare att skilja bokstäver åt.", th: "Atkinson Hyperlegible ช่วยให้แยกตัวอักษรได้ง่ายขึ้น", tr: "Atkinson Hyperlegible harfleri ayırt etmeyi kolaylaştırır.", uk: "Atkinson Hyperlegible полегшує розрізнення літер.", vi: "Atkinson Hyperlegible giúp phân biệt các chữ cái dễ hơn." }
};
