export const libraryMessages: Record<string, Record<string, string>> = {
  "Your collection": { ar: "مجموعتك", bg: "Вашата колекция", "zh-Hans": "你的收藏", "zh-Hant": "你的收藏", cs: "Vaše kolekce", da: "Din samling", nl: "Jouw collectie", fi: "Kokoelmasi", fr: "Votre collection", de: "Deine Sammlung", el: "Η συλλογή σας", hu: "Gyűjteményed", id: "Koleksi Anda", it: "La tua raccolta", ja: "あなたのコレクション", ko: "내 컬렉션", no: "Samlingen din", pl: "Twoja kolekcja", pt: "A tua coleção", "pt-BR": "Sua coleção", ro: "Colecția ta", ru: "Ваша коллекция", es: "Tu colección", sv: "Din samling", th: "คอลเลกชันของคุณ", tr: "Koleksiyonun", uk: "Ваша колекція", vi: "Bộ sưu tập của bạn" },
  "Continue playing": { ar: "تابع اللعب", bg: "Продължете да играете", "zh-Hans": "继续游玩", "zh-Hant": "繼續遊玩", cs: "Pokračovat ve hraní", da: "Fortsæt med at spille", nl: "Verder spelen", fi: "Jatka pelaamista", fr: "Reprendre la partie", de: "Weiterspielen", el: "Συνεχίστε το παιχνίδι", hu: "Játék folytatása", id: "Lanjut bermain", it: "Continua a giocare", ja: "続きをプレイ", ko: "계속 플레이", no: "Fortsett å spille", pl: "Kontynuuj grę", pt: "Continuar a jogar", "pt-BR": "Continuar jogando", ro: "Continuă jocul", ru: "Продолжить игру", es: "Seguir jugando", sv: "Fortsätt spela", th: "เล่นต่อ", tr: "Oynamaya devam et", uk: "Продовжити гру", vi: "Tiếp tục chơi" },
  "Add Piko": { ar: "إضافة Piko", bg: "Добавяне на Piko", "zh-Hans": "添加 Piko", "zh-Hant": "新增 Piko", cs: "Přidat Piko", da: "Tilføj Piko", nl: "Piko toevoegen", fi: "Lisää Piko", fr: "Ajouter un Piko", de: "Piko hinzufügen", el: "Προσθήκη Piko", hu: "Piko hozzáadása", id: "Tambahkan Piko", it: "Aggiungi Piko", ja: "Piko を追加", ko: "Piko 추가", no: "Legg til Piko", pl: "Dodaj Piko", pt: "Adicionar Piko", "pt-BR": "Adicionar Piko", ro: "Adaugă Piko", ru: "Добавить Piko", es: "Añadir Piko", sv: "Lägg till Piko", th: "เพิ่ม Piko", tr: "Piko ekle", uk: "Додати Piko", vi: "Thêm Piko" },
  "What should I play?": { ar: "ماذا ألعب؟", bg: "Какво да играя?", "zh-Hans": "我该玩什么？", "zh-Hant": "我該玩什麼？", cs: "Co si mám zahrát?", da: "Hvad skal jeg spille?", nl: "Wat zal ik spelen?", fi: "Mitä pelaisin?", fr: "À quoi jouer ?", de: "Was soll ich spielen?", el: "Τι να παίξω;", hu: "Mit játsszak?", id: "Apa yang harus saya mainkan?", it: "A cosa gioco?", ja: "何をプレイしよう？", ko: "무엇을 플레이할까요?", no: "Hva skal jeg spille?", pl: "W co zagrać?", pt: "O que devo jogar?", "pt-BR": "O que devo jogar?", ro: "Ce să joc?", ru: "Во что поиграть?", es: "¿A qué juego?", sv: "Vad ska jag spela?", th: "ฉันควรเล่นอะไรดี", tr: "Ne oynasam?", uk: "У що пограти?", vi: "Nên chơi gì?" },
  "Done selecting": { ar: "إنهاء التحديد", bg: "Готово с избора", "zh-Hans": "完成选择", "zh-Hant": "完成選取", cs: "Dokončit výběr", da: "Færdig med at vælge", nl: "Selecteren voltooid", fi: "Valmis valitsemaan", fr: "Terminer la sélection", de: "Auswahl abschließen", el: "Ολοκλήρωση επιλογής", hu: "Kijelölés kész", id: "Selesai memilih", it: "Termina selezione", ja: "選択を完了", ko: "선택 완료", no: "Ferdig med å velge", pl: "Zakończ wybieranie", pt: "Concluir seleção", "pt-BR": "Concluir seleção", ro: "Finalizare selecție", ru: "Завершить выбор", es: "Terminar selección", sv: "Klar med valet", th: "เลือกเสร็จแล้ว", tr: "Seçimi bitir", uk: "Завершити вибір", vi: "Hoàn tất lựa chọn" },
  "Select": { ar: "تحديد", bg: "Избор", "zh-Hans": "选择", "zh-Hant": "選取", cs: "Vybrat", da: "Vælg", nl: "Selecteren", fi: "Valitse", fr: "Sélectionner", de: "Auswählen", el: "Επιλογή", hu: "Kijelölés", id: "Pilih", it: "Seleziona", ja: "選択", ko: "선택", no: "Velg", pl: "Wybierz", pt: "Selecionar", "pt-BR": "Selecionar", ro: "Selectează", ru: "Выбрать", es: "Seleccionar", sv: "Välj", th: "เลือก", tr: "Seç", uk: "Вибрати", vi: "Chọn" },
  "Sort by": { ar: "ترتيب حسب", bg: "Сортиране по", "zh-Hans": "排序方式", "zh-Hant": "排序方式", cs: "Seřadit podle", da: "Sortér efter", nl: "Sorteren op", fi: "Lajitteluperuste", fr: "Trier par", de: "Sortieren nach", el: "Ταξινόμηση κατά", hu: "Rendezés", id: "Urutkan berdasarkan", it: "Ordina per", ja: "並べ替え", ko: "정렬 기준", no: "Sorter etter", pl: "Sortuj według", pt: "Ordenar por", "pt-BR": "Ordenar por", ro: "Sortează după", ru: "Сортировать по", es: "Ordenar por", sv: "Sortera efter", th: "จัดเรียงตาม", tr: "Şuna göre sırala", uk: "Сортувати за", vi: "Sắp xếp theo" },
  "No games match.": { ar: "لا توجد ألعاب مطابقة.", bg: "Няма съвпадащи игри.", "zh-Hans": "没有匹配的游戏。", "zh-Hant": "沒有符合條件的遊戲。", cs: "Žádné hry neodpovídají.", da: "Ingen spil matcher.", nl: "Geen overeenkomende games.", fi: "Yksikään peli ei täsmää.", fr: "Aucun jeu correspondant.", de: "Keine passenden Spiele.", el: "Δεν υπάρχουν παιχνίδια που να ταιριάζουν.", hu: "Nincs egyező játék.", id: "Tidak ada game yang cocok.", it: "Nessun gioco corrispondente.", ja: "一致するゲームがありません。", ko: "일치하는 게임이 없습니다.", no: "Ingen spill samsvarer.", pl: "Brak pasujących gier.", pt: "Não há jogos correspondentes.", "pt-BR": "Nenhum jogo corresponde.", ro: "Niciun joc nu corespunde.", ru: "Подходящих игр нет.", es: "No hay juegos coincidentes.", sv: "Inga matchande spel.", th: "ไม่พบเกมที่ตรงกัน", tr: "Eşleşen oyun yok.", uk: "Немає відповідних ігор.", vi: "Không có trò chơi phù hợp." },
  "Good evening": { ar: "مساء الخير", bg: "Добър вечер", "zh-Hans": "晚上好", "zh-Hant": "晚安", cs: "Dobrý večer", da: "God aften", nl: "Goedenavond", fi: "Hyvää iltaa", fr: "Bonsoir", de: "Guten Abend", el: "Καλησπέρα", hu: "Jó estét", id: "Selamat malam", it: "Buonasera", ja: "こんばんは", ko: "안녕하세요", no: "God kveld", pl: "Dobry wieczór", pt: "Boa noite", "pt-BR": "Boa noite", ro: "Bună seara", ru: "Добрый вечер", es: "Buenas noches", sv: "God kväll", th: "สวัสดีตอนเย็น", tr: "İyi akşamlar", uk: "Добрий вечір", vi: "Chào buổi tối" },
  "Good morning": { ar: "صباح الخير", bg: "Добро утро", "zh-Hans": "早上好", "zh-Hant": "早安", cs: "Dobré ráno", da: "Godmorgen", nl: "Goedemorgen", fi: "Hyvää huomenta", fr: "Bonjour", de: "Guten Morgen", el: "Καλημέρα", hu: "Jó reggelt", id: "Selamat pagi", it: "Buongiorno", ja: "おはようございます", ko: "좋은 아침입니다", no: "God morgen", pl: "Dzień dobry", pt: "Bom dia", "pt-BR": "Bom dia", ro: "Bună dimineața", ru: "Доброе утро", es: "Buenos días", sv: "God morgon", th: "สวัสดีตอนเช้า", tr: "Günaydın", uk: "Доброго ранку", vi: "Chào buổi sáng" },
  "Good afternoon": { ar: "طاب يومك", bg: "Добър ден", "zh-Hans": "下午好", "zh-Hant": "午安", cs: "Dobré odpoledne", da: "God eftermiddag", nl: "Goedemiddag", fi: "Hyvää iltapäivää", fr: "Bon après-midi", de: "Guten Tag", el: "Καλό απόγευμα", hu: "Jó napot", id: "Selamat siang", it: "Buon pomeriggio", ja: "こんにちは", ko: "좋은 오후입니다", no: "God ettermiddag", pl: "Dzień dobry", pt: "Boa tarde", "pt-BR": "Boa tarde", ro: "Bună ziua", ru: "Добрый день", es: "Buenas tardes", sv: "God eftermiddag", th: "สวัสดีตอนบ่าย", tr: "Tünaydın", uk: "Доброго дня", vi: "Chào buổi chiều" }
};
