export const accountHardwareMessages: Record<string, Record<string, string>> = {
  "Manage Tofus": {ar:"إدارة Tofus",bg:"Управление на Tofu","zh-Hans":"管理 Tofu","zh-Hant":"管理 Tofu",cs:"Spravovat Tofu",da:"Administrer Tofu",nl:"Tofus beheren",fi:"Hallitse Tofuja",fr:"Gérer les Tofus",de:"Tofus verwalten",el:"Διαχείριση Tofu",hu:"Tofuk kezelése",id:"Kelola Tofu",it:"Gestisci Tofu",ja:"Tofu を管理",ko:"Tofu 관리",no:"Administrer Tofu",pl:"Zarządzaj Tofu",pt:"Gerir Tofus","pt-BR":"Gerenciar Tofus",ro:"Gestionează Tofu",ru:"Управление Tofu",es:"Administrar Tofus",sv:"Hantera Tofu",th:"จัดการ Tofu",tr:"Tofu'ları yönet",uk:"Керування Tofu",vi:"Quản lý Tofu"},
  "Tofus": {ar:"Tofus",bg:"Tofu","zh-Hans":"Tofu","zh-Hant":"Tofu",cs:"Tofu",da:"Tofu",nl:"Tofu",fi:"Tofut",fr:"Tofus",de:"Tofus",el:"Tofu",hu:"Tofuk",id:"Tofu",it:"Tofu",ja:"Tofu",ko:"Tofu",no:"Tofu",pl:"Tofu",pt:"Tofus","pt-BR":"Tofus",ro:"Tofu",ru:"Tofu",es:"Tofus",sv:"Tofu",th:"Tofu",tr:"Tofu",uk:"Tofu",vi:"Tofu"},
  "Runtime label": {ar:"تسمية بيئة التشغيل",bg:"Етикет на средата за изпълнение","zh-Hans":"运行时标签","zh-Hant":"執行階段標籤",cs:"Označení běhového prostředí",da:"Runtime-etiket",nl:"Runtime-label",fi:"Suoritusaikainen tunniste",fr:"Libellé d’exécution",de:"Laufzeitbezeichnung",el:"Ετικέτα περιβάλλοντος εκτέλεσης",hu:"Futási címke",id:"Label runtime",it:"Etichetta runtime",ja:"ランタイムラベル",ko:"런타임 레이블",no:"Runtime-etikett",pl:"Etykieta środowiska uruchomieniowego",pt:"Etiqueta de execução","pt-BR":"Rótulo de runtime",ro:"Etichetă runtime",ru:"Метка среды выполнения",es:"Etiqueta de ejecución",sv:"Körtidsetikett",th:"ป้ายกำกับรันไทม์",tr:"Çalışma zamanı etiketi",uk:"Мітка середовища виконання",vi:"Nhãn môi trường chạy"},
  "Modpack": {ar:"حزمة تعديلات",bg:"Модпак","zh-Hans":"整合包","zh-Hant":"模組包",cs:"Modpack",da:"Modpakke",nl:"Modpack",fi:"Modipaketti",fr:"Modpack",de:"Modpack",el:"Modpack",hu:"Modpack",id:"Modpack",it:"Modpack",ja:"Modpack",ko:"모드팩",no:"Modpakke",pl:"Modpack",pt:"Modpack","pt-BR":"Modpack",ro:"Modpack",ru:"Сборка модов",es:"Modpack",sv:"Modpack",th:"Modpack",tr:"Mod paketi",uk:"Модпак",vi:"Gói mod"},
  "Name": {ar:"الاسم",bg:"Име","zh-Hans":"名称","zh-Hant":"名稱",cs:"Název",da:"Navn",nl:"Naam",fi:"Nimi",fr:"Nom",de:"Name",el:"Όνομα",hu:"Név",id:"Nama",it:"Nome",ja:"名前",ko:"이름",no:"Navn",pl:"Nazwa",pt:"Nome","pt-BR":"Nome",ro:"Nume",ru:"Название",es:"Nombre",sv:"Namn",th:"ชื่อ",tr:"Ad",uk:"Назва",vi:"Tên"},
  "Save and retry": {ar:"حفظ وإعادة المحاولة",bg:"Запазване и повторен опит","zh-Hans":"保存并重试","zh-Hant":"儲存並重試",cs:"Uložit a zkusit znovu",da:"Gem og prøv igen",nl:"Opslaan en opnieuw proberen",fi:"Tallenna ja yritä uudelleen",fr:"Enregistrer et réessayer",de:"Speichern und erneut versuchen",el:"Αποθήκευση και επανάληψη",hu:"Mentés és újrapróbálás",id:"Simpan dan coba lagi",it:"Salva e riprova",ja:"保存して再試行",ko:"저장 후 다시 시도",no:"Lagre og prøv igjen",pl:"Zapisz i ponów próbę",pt:"Guardar e tentar novamente","pt-BR":"Salvar e tentar novamente",ro:"Salvează și reîncearcă",ru:"Сохранить и повторить",es:"Guardar y volver a intentar",sv:"Spara och försök igen",th:"บันทึกแล้วลองอีกครั้ง",tr:"Kaydet ve yeniden dene",uk:"Зберегти й повторити",vi:"Lưu và thử lại"},
  "SteamID64 (optional)": {ar:"SteamID64 (اختياري)",bg:"SteamID64 (по избор)","zh-Hans":"SteamID64（可选）","zh-Hant":"SteamID64（選填）",cs:"SteamID64 (volitelné)",da:"SteamID64 (valgfrit)",nl:"SteamID64 (optioneel)",fi:"SteamID64 (valinnainen)",fr:"SteamID64 (facultatif)",de:"SteamID64 (optional)",el:"SteamID64 (προαιρετικό)",hu:"SteamID64 (nem kötelező)",id:"SteamID64 (opsional)",it:"SteamID64 (facoltativo)",ja:"SteamID64（任意）",ko:"SteamID64(선택 사항)",no:"SteamID64 (valgfritt)",pl:"SteamID64 (opcjonalnie)",pt:"SteamID64 (opcional)","pt-BR":"SteamID64 (opcional)",ro:"SteamID64 (opțional)",ru:"SteamID64 (необязательно)",es:"SteamID64 (opcional)",sv:"SteamID64 (valfritt)",th:"SteamID64 (ไม่บังคับ)",tr:"SteamID64 (isteğe bağlı)",uk:"SteamID64 (необов’язково)",vi:"SteamID64 (không bắt buộc)"},
  "Steam Web API key (optional)": {ar:"مفتاح Steam Web API (اختياري)",bg:"Steam Web API ключ (по избор)","zh-Hans":"Steam Web API 密钥（可选）","zh-Hant":"Steam Web API 金鑰（選填）",cs:"Klíč Steam Web API (volitelný)",da:"Steam Web API-nøgle (valgfri)",nl:"Steam Web API-sleutel (optioneel)",fi:"Steam Web API -avain (valinnainen)",fr:"Clé Steam Web API (facultative)",de:"Steam-Web-API-Schlüssel (optional)",el:"Κλειδί Steam Web API (προαιρετικό)",hu:"Steam Web API-kulcs (nem kötelező)",id:"Kunci Steam Web API (opsional)",it:"Chiave Steam Web API (facoltativa)",ja:"Steam Web API キー（任意）",ko:"Steam Web API 키(선택 사항)",no:"Steam Web API-nøkkel (valgfri)",pl:"Klucz Steam Web API (opcjonalny)",pt:"Chave Steam Web API (opcional)","pt-BR":"Chave Steam Web API (opcional)",ro:"Cheie Steam Web API (opțională)",ru:"Ключ Steam Web API (необязательно)",es:"Clave de Steam Web API (opcional)",sv:"Steam Web API-nyckel (valfri)",th:"คีย์ Steam Web API (ไม่บังคับ)",tr:"Steam Web API anahtarı (isteğe bağlı)",uk:"Ключ Steam Web API (необов’язково)",vi:"Khóa Steam Web API (không bắt buộc)"},
  "32 character key": {ar:"مفتاح من 32 حرفًا",bg:"Ключ с 32 символа","zh-Hans":"32 位密钥","zh-Hant":"32 個字元的金鑰",cs:"32znakový klíč",da:"Nøgle på 32 tegn",nl:"Sleutel van 32 tekens",fi:"32 merkin avain",fr:"Clé de 32 caractères",de:"32-stelliger Schlüssel",el:"Κλειδί 32 χαρακτήρων",hu:"32 karakteres kulcs",id:"Kunci 32 karakter",it:"Chiave di 32 caratteri",ja:"32 文字のキー",ko:"32자 키",no:"Nøkkel på 32 tegn",pl:"Klucz 32-znakowy",pt:"Chave de 32 caracteres","pt-BR":"Chave de 32 caracteres",ro:"Cheie de 32 de caractere",ru:"Ключ из 32 символов",es:"Clave de 32 caracteres",sv:"Nyckel med 32 tecken",th:"คีย์ 32 ตัวอักษร",tr:"32 karakterli anahtar",uk:"Ключ із 32 символів",vi:"Khóa gồm 32 ký tự"},
  "Open on ProtonDB": {ar:"افتح على ProtonDB",bg:"Отваряне в ProtonDB","zh-Hans":"在 ProtonDB 中打开","zh-Hant":"在 ProtonDB 中開啟",cs:"Otevřít na ProtonDB",da:"Åbn på ProtonDB",nl:"Openen op ProtonDB",fi:"Avaa ProtonDB:ssä",fr:"Ouvrir sur ProtonDB",de:"Auf ProtonDB öffnen",el:"Άνοιγμα στο ProtonDB",hu:"Megnyitás a ProtonDB-n",id:"Buka di ProtonDB",it:"Apri su ProtonDB",ja:"ProtonDB で開く",ko:"ProtonDB에서 열기",no:"Åpne på ProtonDB",pl:"Otwórz w ProtonDB",pt:"Abrir no ProtonDB","pt-BR":"Abrir no ProtonDB",ro:"Deschide pe ProtonDB",ru:"Открыть на ProtonDB",es:"Abrir en ProtonDB",sv:"Öppna på ProtonDB",th:"เปิดใน ProtonDB",tr:"ProtonDB'de aç",uk:"Відкрити на ProtonDB",vi:"Mở trên ProtonDB"}
};
