export const smartFilterMessages: Record<string, Record<string, string>> = {
"Favourites": {ar:"المفضلة",bg:"Любими","zh-Hans":"收藏","zh-Hant":"收藏",cs:"Oblíbené",da:"Favoritter",nl:"Favorieten",fi:"Suosikit",fr:"Favoris",de:"Favoriten",el:"Αγαπημένα",hu:"Kedvencek",id:"Favorit",it:"Preferiti",ja:"お気に入り",ko:"즐겨찾기",no:"Favoritter",pl:"Ulubione",pt:"Favoritos","pt-BR":"Favoritos",ro:"Favorite",ru:"Избранное",es:"Favoritos",sv:"Favoriter",th:"รายการโปรด",tr:"Favoriler",uk:"Улюблене",vi:"Yêu thích"},
"Installed": {ar:"مثبتة",bg:"Инсталирани","zh-Hans":"已安装","zh-Hant":"已安裝",cs:"Nainstalované",da:"Installeret",nl:"Geïnstalleerd",fi:"Asennetut",fr:"Installés",de:"Installiert",el:"Εγκατεστημένα",hu:"Telepítve",id:"Terpasang",it:"Installati",ja:"インストール済み",ko:"설치됨",no:"Installert",pl:"Zainstalowane",pt:"Instalados","pt-BR":"Instalados",ro:"Instalate",ru:"Установленные",es:"Instalados",sv:"Installerade",th:"ติดตั้งแล้ว",tr:"Yüklü",uk:"Встановлені",vi:"Đã cài đặt"},
"Recently played": {ar:"لُعبت مؤخرًا",bg:"Играни наскоро","zh-Hans":"最近游玩","zh-Hant":"最近遊玩",cs:"Nedávno hrané",da:"Spillet for nylig",nl:"Recent gespeeld",fi:"Viimeksi pelatut",fr:"Récemment joués",de:"Zuletzt gespielt",el:"Παίχτηκαν πρόσφατα",hu:"Nemrég játszott",id:"Baru dimainkan",it:"Giocati di recente",ja:"最近プレイしたゲーム",ko:"최근 플레이",no:"Spilt nylig",pl:"Ostatnio grane",pt:"Jogados recentemente","pt-BR":"Jogados recentemente",ro:"Jucate recent",ru:"Недавно играли",es:"Jugados recientemente",sv:"Spelade nyligen",th:"เล่นล่าสุด",tr:"Son oynananlar",uk:"Нещодавно зіграні",vi:"Chơi gần đây"},
"Unplayed": {ar:"لم تُلعب",bg:"Неиграни","zh-Hans":"未游玩","zh-Hant":"未遊玩",cs:"Neh r ané",da:"Ikke spillet",nl:"Niet gespeeld",fi:"Pelaamattomat",fr:"Non joués",de:"Ungespielt",el:"Δεν παίχτηκαν",hu:"Nem játszott",id:"Belum dimainkan",it:"Non giocati",ja:"未プレイ",ko:"미플레이",no:"Ikke spilt",pl:"Niegrane",pt:"Não jogados","pt-BR":"Não jogados",ro:"Nejucate",ru:"Не играли",es:"Sin jugar",sv:"Ospelade",th:"ยังไม่เคยเล่น",tr:"Oynanmamış",uk:"Не зіграні",vi:"Chưa chơi"},
"Most played": {ar:"الأكثر لعبًا",bg:"Най-играни","zh-Hans":"游玩最多","zh-Hant":"遊玩最多",cs:"Nejhranější",da:"Mest spillede",nl:"Meest gespeeld",fi:"Eniten pelatut",fr:"Les plus joués",de:"Am häufigsten gespielt",el:"Περισσότερο παιγμένα",hu:"Legtöbbet játszott",id:"Paling sering dimainkan",it:"Più giocati",ja:"プレイ時間が長い順",ko:"가장 많이 플레이",no:"Mest spilt",pl:"Najczęściej grane",pt:"Mais jogados","pt-BR":"Mais jogados",ro:"Cele mai jucate",ru:"Самые играемые",es:"Más jugados",sv:"Mest spelade",th:"เล่นมากที่สุด",tr:"En çok oynanan",uk:"Найбільш зіграні",vi:"Chơi nhiều nhất"},
"Game launchers": {ar:"مشغّلات الألعاب",bg:"Стартери за игри","zh-Hans":"游戏启动器","zh-Hant":"遊戲啟動器",cs:"Herní launchery",da:"Spil-launchere",nl:"Game-launchers",fi:"Pelien käynnistimet",fr:"Launchers de jeux",de:"Game-Launcher",el:"Launchers παιχνιδιών",hu:"Játékindítók",id:"Peluncur game",it:"Launcher di giochi",ja:"ゲームランチャー",ko:"게임 런처",no:"Spillstartere",pl:"Launchery gier",pt:"Launchers de jogos","pt-BR":"Launchers de jogos",ro:"Launchere de jocuri",ru:"Игровые лаунчеры",es:"Launchers de juegos",sv:"Spelstartare",th:"ตัวเรียกใช้เกม",tr:"Oyun başlatıcıları",uk:"Ігрові лаунчери",vi:"Trình khởi chạy trò chơi"},
"Running": {ar:"قيد التشغيل",bg:"Работещи","zh-Hans":"正在运行","zh-Hant":"正在執行",cs:"Spuštěné",da:"Kører",nl:"Actief",fi:"Käynnissä",fr:"En cours d’exécution",de:"Wird ausgeführt",el:"Σε εκτέλεση",hu:"Fut",id:"Berjalan",it:"In esecuzione",ja:"実行中",ko:"실행 중",no:"Kjører",pl:"Uruchomione",pt:"Em execução","pt-BR":"Em execução",ro:"În execuție",ru:"Запущенные",es:"En ejecución",sv:"Körs",th:"กำลังทำงาน",tr:"Çalışıyor",uk:"Запущені",vi:"Đang chạy"},
"Backlog": {ar:"قائمة الانتظار",bg:"Списък за игра","zh-Hans":"待玩列表","zh-Hant":"待玩清單",cs:"Seznam her",da:"Spilliste",nl:"Backlog",fi:"Pelit",fr:"Liste de jeux",de:"Backlog",el:"Λίστα παιχνιδιών",hu:"Várólista",id:"Daftar game",it:"Lista giochi",ja:"バックログ",ko:"대기 목록",no:"Spilliste",pl:"Lista gier",pt:"Lista de jogos","pt-BR":"Lista de jogos",ro:"Listă de jocuri",ru:"Список игр",es:"Lista de juegos",sv:"Spelkö",th:"รายการเกม",tr:"Oyun listesi",uk:"Список ігор",vi:"Danh sách chờ"},
"Grid": {ar:"شبكة",bg:"Мрежа","zh-Hans":"网格","zh-Hant":"網格",cs:"Mřížka",da:"Gitter",nl:"Raster",fi:"Ruudukko",fr:"Grille",de:"Raster",el:"Πλέγμα",hu:"Rács",id:"Kisi",it:"Griglia",ja:"グリッド",ko:"그리드",no:"Rutenett",pl:"Siatka",pt:"Grelha","pt-BR":"Grade",ro:"Grilă",ru:"Сетка",es:"Cuadrícula",sv:"Rutnät",th:"ตาราง",tr:"Izgara",uk:"Сітка",vi:"Lưới"},
"Compact grid": {ar:"شبكة مضغوطة",bg:"Компактна мрежа","zh-Hans":"紧凑网格","zh-Hant":"緊湊網格",cs:"Kompaktní mřížka",da:"Kompakt gitter",nl:"Compact raster",fi:"Tiivis ruudukko",fr:"Grille compacte",de:"Kompaktes Raster",el:"Συμπαγές πλέγμα",hu:"Kompakt rács",id:"Kisi ringkas",it:"Griglia compatta",ja:"コンパクトグリッド",ko:"컴팩트 그리드",no:"Kompakt rutenett",pl:"Kompaktowa siatka",pt:"Grelha compacta","pt-BR":"Grade compacta",ro:"Grilă compactă",ru:"Компактная сетка",es:"Cuadrícula compacta",sv:"Kompakt rutnät",th:"ตารางขนาดกะทัดรัด",tr:"Kompakt ızgara",uk:"Компактна сітка",vi:"Lưới gọn"},
"List": {ar:"قائمة",bg:"Списък","zh-Hans":"列表","zh-Hant":"清單",cs:"Seznam",da:"Liste",nl:"Lijst",fi:"Luettelo",fr:"Liste",de:"Liste",el:"Λίστα",hu:"Lista",id:"Daftar",it:"Elenco",ja:"リスト",ko:"목록",no:"Liste",pl:"Lista",pt:"Lista","pt-BR":"Lista",ro:"Listă",ru:"Список",es:"Lista",sv:"Lista",th:"รายการ",tr:"Liste",uk:"Список",vi:"Danh sách"},
"Shelves": {ar:"رفوف",bg:"Рафтове","zh-Hans":"分架","zh-Hant":"分架",cs:"Police",da:"Hylder",nl:"Planken",fi:"Hyllyt",fr:"Étagères",de:"Regale",el:"Ράφια",hu:"Polcok",id:"Rak",it:"Scaffali",ja:"シェルフ",ko:"선반",no:"Hyller",pl:"Półki",pt:"Prateleiras","pt-BR":"Prateleiras",ro:"Rafturi",ru:"Полки",es:"Estantes",sv:"Hyllor",th:"ชั้นวาง",tr:"Raflar",uk:"Полиці",vi:"Kệ"},
"Large cards": {ar:"بطاقات كبيرة",bg:"Големи карти","zh-Hans":"大卡片","zh-Hant":"大型卡片",cs:"Velké karty",da:"Store kort",nl:"Grote kaarten",fi:"Suuret kortit",fr:"Grandes cartes",de:"Große Karten",el:"Μεγάλες κάρτες",hu:"Nagy kártyák",id:"Kartu besar",it:"Schede grandi",ja:"大きなカード",ko:"큰 카드",no:"Store kort",pl:"Duże karty",pt:"Cartões grandes","pt-BR":"Cartões grandes",ro:"Carduri mari",ru:"Большие карточки",es:"Tarjetas grandes",sv:"Stora kort",th:"การ์ดขนาดใหญ่",tr:"Büyük kartlar",uk:"Великі картки",vi:"Thẻ lớn"}
};