export const launchOptionsMessages: Record<string, Record<string, string>> = {
  "Launch settings": {ar:"إعدادات التشغيل",bg:"Настройки за стартиране","zh-Hans":"启动设置","zh-Hant":"啟動設定",cs:"Nastavení spuštění",da:"Startindstillinger",nl:"Startinstellingen",fi:"Käynnistysasetukset",fr:"Paramètres de lancement",de:"Starteinstellungen",el:"Ρυθμίσεις εκκίνησης",hu:"Indítási beállítások",id:"Pengaturan peluncuran",it:"Impostazioni di avvio",ja:"起動設定",ko:"실행 설정",no:"Startinnstillinger",pl:"Ustawienia uruchamiania",pt:"Definições de arranque","pt-BR":"Configurações de inicialização",ro:"Setări de lansare",ru:"Настройки запуска",es:"Ajustes de inicio",sv:"Startinställningar",th:"การตั้งค่าการเปิดเกม",tr:"Başlatma ayarları",uk:"Налаштування запуску",vi:"Cài đặt khởi chạy"},
  "Compatibility runtime": {ar:"بيئة تشغيل التوافق",bg:"Среда за съвместимост","zh-Hans":"兼容运行环境","zh-Hant":"相容性執行環境",cs:"Kompatibilní běhové prostředí",da:"Kompatibilitetsruntime",nl:"Compatibiliteitsruntime",fi:"Yhteensopivuusympäristö",fr:"Environnement de compatibilité",de:"Kompatibilitätslaufzeit",el:"Περιβάλλον εκτέλεσης συμβατότητας",hu:"Kompatibilitási futtatókörnyezet",id:"Runtime kompatibilitas",it:"Runtime di compatibilità",ja:"互換性ランタイム",ko:"호환성 런타임",no:"Kompatibilitetsruntime",pl:"Środowisko zgodności",pt:"Ambiente de compatibilidade","pt-BR":"Ambiente de compatibilidade",ro:"Runtime de compatibilitate",ru:"Среда совместимости",es:"Entorno de compatibilidad",sv:"Kompatibilitetsruntime",th:"รันไทม์ความเข้ากันได้",tr:"Uyumluluk çalışma zamanı",uk:"Середовище сумісності",vi:"Môi trường tương thích"},
  "Wrappers": {ar:"أغلفة التشغيل",bg:"Обвивки","zh-Hans":"包装器","zh-Hant":"包裝器",cs:"Obaly",da:"Wrappere",nl:"Wrappers",fi:"Kääreet",fr:"Wrappers",de:"Wrapper",el:"Wrappers",hu:"Burkolók",id:"Wrapper",it:"Wrapper",ja:"ラッパー",ko:"래퍼",no:"Wrappere",pl:"Wrappery",pt:"Wrappers","pt-BR":"Wrappers",ro:"Wrapper-e",ru:"Обёртки",es:"Wrappers",sv:"Wrappers",th:"Wrapper",tr:"Sarmalayıcılar",uk:"Обгортки",vi:"Trình bao"},
  "Launch arguments": {ar:"وسائط التشغيل",bg:"Аргументи за стартиране","zh-Hans":"启动参数","zh-Hant":"啟動參數",cs:"Argumenty spuštění",da:"Startargumenter",nl:"Startargumenten",fi:"Käynnistysargumentit",fr:"Arguments de lancement",de:"Startargumente",el:"Ορίσματα εκκίνησης",hu:"Indítási argumentumok",id:"Argumen peluncuran",it:"Argomenti di avvio",ja:"起動引数",ko:"실행 인수",no:"Startargumenter",pl:"Argumenty uruchamiania",pt:"Argumentos de arranque","pt-BR":"Argumentos de inicialização",ro:"Argumente de lansare",ru:"Аргументы запуска",es:"Argumentos de inicio",sv:"Startargument",th:"อาร์กิวเมนต์การเปิดเกม",tr:"Başlatma bağımsız değişkenleri",uk:"Аргументи запуску",vi:"Tham số khởi chạy"},
  "Environment variables": {ar:"متغيرات البيئة",bg:"Променливи на средата","zh-Hans":"环境变量","zh-Hant":"環境變數",cs:"Proměnné prostředí",da:"Miljøvariabler",nl:"Omgevingsvariabelen",fi:"Ympäristömuuttujat",fr:"Variables d’environnement",de:"Umgebungsvariablen",el:"Μεταβλητές περιβάλλοντος",hu:"Környezeti változók",id:"Variabel lingkungan",it:"Variabili d'ambiente",ja:"環境変数",ko:"환경 변수",no:"Miljøvariabler",pl:"Zmienne środowiskowe",pt:"Variáveis de ambiente","pt-BR":"Variáveis de ambiente",ro:"Variabile de mediu",ru:"Переменные окружения",es:"Variables de entorno",sv:"Miljövariabler",th:"ตัวแปรสภาพแวดล้อม",tr:"Ortam değişkenleri",uk:"Змінні середовища",vi:"Biến môi trường"},
  "Working directory": {ar:"مجلد العمل",bg:"Работна директория","zh-Hans":"工作目录","zh-Hant":"工作目錄",cs:"Pracovní adresář",da:"Arbejdsmappe",nl:"Werkmap",fi:"Työhakemisto",fr:"Répertoire de travail",de:"Arbeitsverzeichnis",el:"Κατάλογος εργασίας",hu:"Munkakönyvtár",id:"Direktori kerja",it:"Directory di lavoro",ja:"作業ディレクトリ",ko:"작업 디렉터리",no:"Arbeidsmappe",pl:"Katalog roboczy",pt:"Diretório de trabalho","pt-BR":"Diretório de trabalho",ro:"Director de lucru",ru:"Рабочий каталог",es:"Directorio de trabajo",sv:"Arbetskatalog",th:"ไดเรกทอรีทำงาน",tr:"Çalışma dizini",uk:"Робочий каталог",vi:"Thư mục làm việc"},
  "Default": {ar:"افتراضي",bg:"По подразбиране","zh-Hans":"默认","zh-Hant":"預設",cs:"Výchozí",da:"Standard",nl:"Standaard",fi:"Oletus",fr:"Par défaut",de:"Standard",el:"Προεπιλογή",hu:"Alapértelmezett",id:"Bawaan",it:"Predefinito",ja:"既定",ko:"기본값",no:"Standard",pl:"Domyślne",pt:"Predefinição","pt-BR":"Padrão",ro:"Implicit",ru:"По умолчанию",es:"Predeterminado",sv:"Standard",th:"ค่าเริ่มต้น",tr:"Varsayılan",uk:"За замовчуванням",vi:"Mặc định"},
  "Choose working directory": {ar:"اختر مجلد العمل",bg:"Избор на работна директория","zh-Hans":"选择工作目录","zh-Hant":"選擇工作目錄",cs:"Vybrat pracovní adresář",da:"Vælg arbejdsmappe",nl:"Werkmap kiezen",fi:"Valitse työhakemisto",fr:"Choisir le répertoire de travail",de:"Arbeitsverzeichnis auswählen",el:"Επιλογή καταλόγου εργασίας",hu:"Munkakönyvtár kiválasztása",id:"Pilih direktori kerja",it:"Scegli directory di lavoro",ja:"作業ディレクトリを選択",ko:"작업 디렉터리 선택",no:"Velg arbeidsmappe",pl:"Wybierz katalog roboczy",pt:"Escolher diretório de trabalho","pt-BR":"Escolher diretório de trabalho",ro:"Alege directorul de lucru",ru:"Выбрать рабочий каталог",es:"Elegir directorio de trabajo",sv:"Välj arbetskatalog",th:"เลือกไดเรกทอรีทำงาน",tr:"Çalışma dizinini seç",uk:"Вибрати робочий каталог",vi:"Chọn thư mục làm việc"},
  "Duplicate": {ar:"تكرار",bg:"Дублиране","zh-Hans":"复制","zh-Hant":"複製",cs:"Duplikovat",da:"Duplikér",nl:"Dupliceren",fi:"Monista",fr:"Dupliquer",de:"Duplizieren",el:"Δημιουργία αντιγράφου",hu:"Duplikálás",id:"Duplikat",it:"Duplica",ja:"複製",ko:"복제",no:"Dupliser",pl:"Duplikuj",pt:"Duplicar","pt-BR":"Duplicar",ro:"Duplică",ru:"Дублировать",es:"Duplicar",sv:"Duplicera",th:"ทำซ้ำ",tr:"Çoğalt",uk:"Дублювати",vi:"Nhân bản"}
};
