// Bundled, offline artwork for launchers (generated by scripts/build-launcher-art.mjs).
const art = import.meta.glob("../assets/launchers/*.svg", { eager: true, query: "?url", import: "default" }) as Record<string, string>;
const icons = import.meta.glob("../assets/launchers/icons/*.svg", { eager: true, query: "?url", import: "default" }) as Record<string, string>;

const byId = (modules: Record<string, string>) =>
  Object.fromEntries(Object.entries(modules).map(([path, url]) => [path.split("/").pop()!.replace(/\.svg$/, ""), url]));
const artById = byId(art);
const iconById = byId(icons);

/** Portrait cover for a launcher entry; falls back to the generic launcher art. */
export const launcherArt = (launcherId?: string | null): string => artById[launcherId ?? ""] ?? artById.launcher ?? "";

/** Square brand tile for a launcher or import source; falls back to the generic glyph. */
export const launcherIcon = (id?: string | null): string => iconById[id ?? ""] ?? iconById.launcher ?? "";
