// Downloads the Google Fonts every built-in theme (plus the app base fonts) needs and writes
// src/styles/fonts.generated.css. Run manually (`node scripts/fetch-fonts.mjs`) when a theme's `fonts`
// list changes; the downloaded files and generated CSS are committed so builds never need network.
import { mkdirSync, readdirSync, readFileSync, rmSync, writeFileSync, existsSync } from "node:fs";
import { join } from "node:path";

const UA = "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36";
const KEEP_SUBSETS = new Set(["latin", "latin-ext"]);
const OUT_DIR = "src/assets/fonts";
const OUT_CSS = "src/styles/fonts.generated.css";

// Fonts used by the base UI (tokens.css / index.css) rather than a single theme.
const EXTRA_URLS = [
  "https://fonts.googleapis.com/css2?family=DM+Sans:wght@400;500;600;700&family=Manrope:wght@500;600;700;800&family=JetBrains+Mono:wght@400;500&display=swap",
];

const slug = (name) => name.toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/^-|-$/g, "");

const urls = new Set(EXTRA_URLS);
for (const entry of readdirSync("src/themes", { withFileTypes: true })) {
  if (!entry.isDirectory()) continue;
  const manifest = JSON.parse(readFileSync(join("src/themes", entry.name, "theme.json"), "utf8"));
  for (const url of manifest.fonts ?? []) urls.add(url);
}

async function get(url, binary) {
  const response = await fetch(url, { headers: { "User-Agent": UA } });
  if (!response.ok) throw new Error(`${url}: HTTP ${response.status}`);
  return binary ? Buffer.from(await response.arrayBuffer()) : response.text();
}

// family -> Map(ruleKey -> rule), so overlapping theme requests collapse.
const rules = new Map();
const files = new Map(); // gstatic url -> relative path (shared by variable-font weights)
if (existsSync(OUT_DIR)) for (const entry of readdirSync(OUT_DIR, { withFileTypes: true })) if (entry.isDirectory()) rmSync(join(OUT_DIR, entry.name), { recursive: true });

for (const url of urls) {
  const cssText = await get(url, false);
  const pattern = /\/\*\s*([\w-]+)\s*\*\/\s*@font-face\s*\{([^}]*)\}/g;
  for (const match of cssText.matchAll(pattern)) {
    const [, subset, body] = match;
    if (!KEEP_SUBSETS.has(subset)) continue;
    const family = /font-family:\s*'([^']+)'/.exec(body)?.[1];
    const style = /font-style:\s*(\w+)/.exec(body)?.[1] ?? "normal";
    const weight = /font-weight:\s*([\d ]+)/.exec(body)?.[1].trim() ?? "400";
    const range = /unicode-range:\s*([^;]+)/.exec(body)?.[1].trim();
    const src = /url\((https:\/\/fonts\.gstatic\.com\/[^)]+\.woff2)\)/.exec(body)?.[1];
    if (!family || !src) continue;
    const dir = slug(family);
    if (!files.has(src)) {
      const name = `${subset}-${weight.replace(/\s+/g, "-")}-${style}.woff2`;
      mkdirSync(join(OUT_DIR, dir), { recursive: true });
      writeFileSync(join(OUT_DIR, dir, name), await get(src, true));
      files.set(src, `${dir}/${name}`);
    }
    const key = `${family}|${style}|${weight}|${subset}`;
    rules.set(key, { family, style, weight, range, subset, file: files.get(src) });
  }
}

const sorted = [...rules.values()].sort((a, b) => a.family.localeCompare(b.family) || a.style.localeCompare(b.style) || a.weight.localeCompare(b.weight, undefined, { numeric: true }) || a.subset.localeCompare(b.subset));
const lines = ["/* Generated by scripts/fetch-fonts.mjs. Do not edit. Licences: src/assets/fonts/LICENSES.md */"];
for (const r of sorted) {
  lines.push(`@font-face {\n  font-family: "${r.family}";\n  font-style: ${r.style};\n  font-weight: ${r.weight};\n  font-display: swap;\n  src: url("../assets/fonts/${r.file}") format("woff2");${r.range ? `\n  unicode-range: ${r.range};` : ""}\n}`);
}
writeFileSync(OUT_CSS, lines.join("\n") + "\n");
const families = [...new Set(sorted.map((r) => r.family))];
console.log(`Wrote ${sorted.length} @font-face rules, ${files.size} files, ${families.length} families: ${families.join(", ")}`);
